import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.167.1/+esm";
import {OrbitControls} from "https://cdn.jsdelivr.net/npm/three@0.167.1/examples/jsm/controls/OrbitControls.js/+esm";
import {TransformControls} from "https://cdn.jsdelivr.net/npm/three@0.167.1/examples/jsm/controls/TransformControls.js/+esm";

const $=id=>document.getElementById(id), viewport=$("viewport");
const scene=new THREE.Scene(); scene.background=new THREE.Color(0xf1efec);
const camera=new THREE.PerspectiveCamera(48,1,.1,500); camera.position.set(32,34,42);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.outputColorSpace=THREE.SRGBColorSpace; viewport.appendChild(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement); orbit.enableDamping=true; orbit.target.set(0,2,0);
const transform=new TransformControls(camera,renderer.domElement); transform.setMode("translate"); transform.showY=false; scene.add(transform);
transform.addEventListener("dragging-changed",e=>orbit.enabled=!e.value);

const palette={lavender:{accent:0xa58cc7,deep:0x725b98,gold:0xcaa85f},amethyst:{accent:0x8870b5,deep:0x5f477f,gold:0xd0ad63},sage:{accent:0x96a890,deep:0x66765f,gold:0xcaa85f},blush:{accent:0xcba7b2,deep:0x98747e,gold:0xcaa85f},blue:{accent:0x96abc8,deep:0x637895,gold:0xcaa85f}};
let themeName="lavender",theme=palette[themeName],floralIntensity=.35,goldIntensity=1.25,selected=null,guests=[],shopping=[];
const floorMat=new THREE.MeshStandardMaterial({color:0x292725,roughness:.7}),danceMat=new THREE.MeshStandardMaterial({color:0x4b4845,roughness:.48}),wallMat=new THREE.MeshStandardMaterial({color:0xf7f4ef,roughness:.95,transparent:true,opacity:.88,side:THREE.DoubleSide}),whiteMat=new THREE.MeshStandardMaterial({color:0xf9f7f3,roughness:.86}),silverMat=new THREE.MeshStandardMaterial({color:0xbec2c6,metalness:.72,roughness:.25}),glassMat=new THREE.MeshStandardMaterial({color:0xcbdce7,transparent:true,opacity:.2,roughness:.15}),accentMat=new THREE.MeshStandardMaterial({color:theme.accent,roughness:.72}),goldMat=new THREE.MeshStandardMaterial({color:theme.gold,metalness:.72,roughness:.24});
scene.add(new THREE.HemisphereLight(0xffffff,0x756b61,2.2)); const sun=new THREE.DirectionalLight(0xffead1,2.8); sun.position.set(-8,22,12); sun.castShadow=true; scene.add(sun);

const shell=new THREE.Group();scene.add(shell),walls=[];
const roomShape=new THREE.Shape(); roomShape.moveTo(-17.5,-31);roomShape.lineTo(17.5,-31);roomShape.lineTo(17.5,1);roomShape.lineTo(9.5,1);roomShape.lineTo(9.5,31);roomShape.lineTo(-17.5,31);roomShape.closePath();
const floor=new THREE.Mesh(new THREE.ShapeGeometry(roomShape),floorMat); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true;shell.add(floor);
const danceShape=new THREE.Shape(); danceShape.moveTo(-6.3,-20);danceShape.lineTo(5,-20);danceShape.lineTo(5,22.5);danceShape.lineTo(-6.3,22.5);danceShape.closePath(); const dance=new THREE.Mesh(new THREE.ShapeGeometry(danceShape),danceMat);dance.rotation.x=-Math.PI/2;dance.position.y=.025;shell.add(dance);
function wall(w,h,d,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),wallMat);m.position.set(x,y,z);m.castShadow=true;shell.add(m);walls.push(m)}
wall(35,12.5,.18,0,6.25,-31);wall(27,12.5,.18,-4,6.25,31);wall(.18,12.5,37,-17.5,6.25,-12.5);wall(.18,12.5,20,-17.5,6.25,21);wall(.18,12.5,32,17.5,6.25,-15);wall(2.2,12.5,.18,16.4,6.25,1);wall(2,12.5,.18,10.5,6.25,1);wall(.18,12.5,20,9.5,6.25,21);wall(.18,12.5,5,9.5,6.25,3.5);
for(let z=-26;z<=-4;z+=7.3){const p=new THREE.Mesh(new THREE.BoxGeometry(.11,7,5.8),glassMat);p.position.set(17.42,6.1,z);shell.add(p)}
const exitSign=new THREE.Mesh(new THREE.BoxGeometry(.12,1.8,3.5),new THREE.MeshStandardMaterial({color:0xb64040}));exitSign.position.set(-17.38,2.3,8.2);shell.add(exitSign);
function door(x,z,ry=0,w=2.7){const d=new THREE.Mesh(new THREE.BoxGeometry(w,7,.12),new THREE.MeshStandardMaterial({color:0xd9d3cb}));d.position.set(x,3.5,z);d.rotation.y=ry;shell.add(d)} door(13.6,1.08,0,2.5);door(11.2,1.08,0,2.5);door(9.42,7,Math.PI/2,2.6);
function chandelier(z){const g=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(2.1,.06,12,48),goldMat);ring.rotation.x=Math.PI/2;g.add(ring);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,l=new THREE.PointLight(0xffd5a0,.38,10);l.position.set(Math.cos(a)*1.8,-.15,Math.sin(a)*1.8);g.add(l)}g.position.set(0,10.8,z);scene.add(g)}chandelier(-15);chandelier(16);

const objects=new Map(),labels=new Map();
function label(text,obj){const el=document.createElement("div");el.textContent=text;Object.assign(el.style,{position:"absolute",fontSize:"11px",background:"rgba(255,255,255,.9)",padding:"3px 6px",borderRadius:"6px",pointerEvents:"none",whiteSpace:"nowrap",border:"1px solid rgba(0,0,0,.08)"});viewport.appendChild(el);labels.set(obj,el)}
function register(id,name,obj,type){obj.userData={id,label:name,type};scene.add(obj);objects.set(id,obj);label(name,obj);return obj}
function chair(){const g=new THREE.Group(),seat=new THREE.Mesh(new THREE.BoxGeometry(.9,.25,.9),whiteMat),back=new THREE.Mesh(new THREE.BoxGeometry(.9,1.45,.18),whiteMat),skirt=new THREE.Mesh(new THREE.CylinderGeometry(.66,.72,1.15,18,1,true),whiteMat);seat.position.y=.62;back.position.set(0,1.3,.34);skirt.position.y=.28;g.add(seat,back,skirt);return g}
function flowers(scale=.95){const g=new THREE.Group(),n=Math.max(3,Math.round(9*floralIntensity));for(let i=0;i<n;i++){const c=i%3===0?theme.deep:(i%2===0?theme.accent:0xf0ece5),m=new THREE.Mesh(new THREE.SphereGeometry(.3,12,9),new THREE.MeshStandardMaterial({color:c})),a=i/n*Math.PI*2,r=.4+.25*Math.random();m.position.set(Math.cos(a)*r,(Math.random()-.2)*.4,Math.sin(a)*r);g.add(m)}g.scale.setScalar(scale);return g}
function table(id,x,z,seats){const g=new THREE.Group(),top=new THREE.Mesh(new THREE.CylinderGeometry(3.05,3.05,.18,48),whiteMat),leg=new THREE.Mesh(new THREE.CylinderGeometry(.27,.5,2.2,20),whiteMat),runner=new THREE.Mesh(new THREE.BoxGeometry(1.05,.045,5.25),accentMat),vase=new THREE.Mesh(new THREE.CylinderGeometry(.34,.48,.65,20),goldMat);top.position.y=2.35;leg.position.y=1.15;runner.position.y=2.47;runner.rotation.y=Math.PI/2;vase.position.y=2.82;g.add(top,leg,runner,vase);const f=flowers();f.position.y=3.35;g.add(f);for(let i=0;i<seats;i++){const a=i/seats*Math.PI*2,c=chair();c.position.set(Math.cos(a)*4,0,Math.sin(a)*4);c.rotation.y=-a+Math.PI/2;g.add(c);const p=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.035,20),whiteMat);p.rotation.x=Math.PI/2;p.position.set(Math.cos(a)*2.4,2.48,Math.sin(a)*2.4);g.add(p);const fork=new THREE.Mesh(new THREE.BoxGeometry(.04,.02,.55),silverMat);fork.position.set(Math.cos(a)*2.65,2.5,Math.sin(a)*2.65);fork.rotation.y=-a;g.add(fork)}g.position.set(x,0,z);g.userData.seats=seats;return register(id,`Table ${id.slice(1)} (${seats})`,g,"table")}
function station(id,name,x,z,w=6,d=2.5){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(w,2.35,d),whiteMat),r=new THREE.Mesh(new THREE.BoxGeometry(w*.24,.05,d+.08),accentMat);b.position.y=1.18;r.position.set(w*.35,2.4,0);g.add(b,r);g.position.set(x,0,z);return register(id,name,g,"station")}
function sweetheart(){const g=station("sweetheart","Bride & Groom",12.2,-13.5,8.5,2.8),arc=new THREE.Mesh(new THREE.TorusGeometry(3.3,.075,14,70,Math.PI),goldMat);arc.rotation.z=Math.PI;arc.position.set(0,5,-.8);g.add(arc);const f=flowers(1.3);f.position.set(-2.1,5.3,-.8);g.add(f)}sweetheart();

const defaultTablePos=[[-12,-23],[-4,-24],[7,-23],[-12,-9],[8,-8],[-12,8],[7,8],[-12,23],[-4,25],[5,23]],stationDefs={photoBooth:["photo","Photo booth",-12,27,7,3],polaroid:["polaroid","Polaroid scrapbook",5,27,6,2.5],video:["video","Video messages",5,16,5,2.3],advice:["advice","Advice jar",5,10,4.5,2.2],cake:["cake","Cake / sweets",-13,16,6.5,2.5],dj:["dj","DJ",-13,-28,6,2.5]};
function remove(id){const o=objects.get(id);if(!o)return;scene.remove(o);labels.get(o)?.remove();labels.delete(o);objects.delete(id);if(selected===o){selected=null;transform.detach()}}
function dist(){const n=Math.max(8,Math.min(10,+$("tableCount").value||10)),t=Math.max(70,Math.min(100,+$("guestTarget").value||95)),b=Math.floor(t/n),e=t%n;return Array.from({length:n},(_,i)=>b+(i<e?1:0))}
function rebuild(){[...objects].filter(([,o])=>o.userData.type==="table").forEach(([id])=>remove(id));const d=dist();d.forEach((s,i)=>table("t"+(i+1),defaultTablePos[i][0],defaultTablePos[i][1],s));$("seatDistribution").textContent=d.map((s,i)=>`T${i+1}: ${s}`).join(" · ");refresh();renderGuests();metrics()}
rebuild();Object.values(stationDefs).forEach(v=>station(...v));
function refresh(){const s=$("selectedObject"),keep=selected?.userData.id;s.innerHTML="";objects.forEach(o=>{const op=document.createElement("option");op.value=o.userData.id;op.textContent=o.userData.label;s.appendChild(op)});if(keep&&objects.has(keep))s.value=keep}
function clamp(){if(!selected)return;selected.position.z=Math.max(-29.5,Math.min(29.5,selected.position.z));const xmax=selected.position.z<=1?16.2:8.2;selected.position.x=Math.max(-16.2,Math.min(xmax,selected.position.x))}
function sync(){if(!selected)return;$("xPos").value=selected.position.x;$("zPos").value=selected.position.z;$("rot").value=(THREE.MathUtils.radToDeg(selected.rotation.y)%360+360)%360;$("scale").value=selected.scale.x}
function select(o){if(!o)return;selected=o;transform.attach(o);$("selectedObject").value=o.userData.id;sync()} transform.addEventListener("objectChange",()=>{clamp();sync()});
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener("pointerdown",e=>{if(transform.dragging)return;const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const h=ray.intersectObjects([...objects.values()],true);if(!h.length)return;let o=h[0].object;while(o.parent&&!o.userData.id)o=o.parent;if(o.userData.id)select(o)});
function applyTheme(n){themeName=n;theme=palette[n];accentMat.color.set(theme.accent);goldMat.color.set(theme.gold);document.documentElement.style.setProperty("--accent","#"+theme.accent.toString(16).padStart(6,"0"));document.documentElement.style.setProperty("--deep","#"+theme.deep.toString(16).padStart(6,"0"));document.documentElement.style.setProperty("--gold","#"+theme.gold.toString(16).padStart(6,"0"));$("swatches").innerHTML=`<span class="swatch" style="background:#faf8f2"></span><span class="swatch" style="background:#${theme.accent.toString(16).padStart(6,"0")}"></span><span class="swatch" style="background:#${theme.deep.toString(16).padStart(6,"0")}"></span><span class="swatch" style="background:#${theme.gold.toString(16).padStart(6,"0")}"></span>`;rebuild()}
$("theme").onchange=e=>applyTheme(e.target.value);$("floralIntensity").oninput=e=>{floralIntensity=+e.target.value;rebuild()};$("goldIntensity").oninput=e=>goldIntensity=+e.target.value;$("rebuild").onclick=rebuild;$("tableCount").onchange=rebuild;$("guestTarget").onchange=rebuild;$("selectedObject").onchange=e=>select(objects.get(e.target.value));$("xPos").oninput=e=>{if(selected){selected.position.x=+e.target.value;clamp();sync()}};$("zPos").oninput=e=>{if(selected){selected.position.z=+e.target.value;clamp();sync()}};$("rot").oninput=e=>{if(selected)selected.rotation.y=THREE.MathUtils.degToRad(+e.target.value)};$("scale").oninput=e=>{if(selected)selected.scale.setScalar(+e.target.value)};$("wallsToggle").onchange=e=>walls.forEach(w=>w.visible=e.target.checked);$("labelsToggle").onchange=e=>labels.forEach(l=>l.style.display=e.target.checked?"block":"none");
Object.entries(stationDefs).forEach(([box,v])=>$(box).onchange=e=>{if(e.target.checked&&!objects.has(v[0]))station(...v);if(!e.target.checked)remove(v[0]);refresh()});
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function renderGuests(){const list=$("guestList");list.innerHTML="";const tables=[...objects.values()].filter(o=>o.userData.type==="table");guests.forEach((g,i)=>{const row=document.createElement("div");row.className="guestRow";const info=document.createElement("div");info.innerHTML=`<div>${esc(g.name)}</div><div class="meta">${esc(g.side)}</div>`;const sel=document.createElement("select");sel.innerHTML='<option value="">Unassigned</option>'+tables.map(o=>`<option value="${o.userData.id}">${o.userData.label}</option>`).join("");sel.value=g.table||"";sel.onchange=()=>{g.table=sel.value;metrics()};const del=document.createElement("button");del.textContent="×";del.onclick=()=>{guests.splice(i,1);renderGuests()};row.append(info,sel,del);list.append(row)});metrics()}
$("addGuest").onclick=()=>{const n=$("guestName").value.trim();if(!n)return;guests.push({name:n,side:$("guestSide").value,table:""});$("guestName").value="";renderGuests()};$("fillDemoGuests").onclick=()=>{guests=[];for(let i=1;i<=95;i++)guests.push({name:`Guest ${i}`,side:i%3===0?"Friends":i%2===0?"Groom family":"Bride family",table:"t"+(((i-1)%10)+1)});renderGuests()};
function renderShopping(){const b=$("shoppingList");b.innerHTML="";let total=0;shopping.forEach((it,i)=>{total+=it.price*it.qty;const r=document.createElement("div");r.className="shopRow";r.innerHTML=`<div><div>${esc(it.name)}</div><div class="meta">${it.url?`<a href="${esc(it.url)}" target="_blank">open link</a>`:"no link"}</div></div><div>×${it.qty}</div><div>$${(it.price*it.qty).toFixed(0)}</div>`;const d=document.createElement("button");d.textContent="×";d.onclick=()=>{shopping.splice(i,1);renderShopping()};r.append(d);b.append(r)});$("budgetTotal").textContent=new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(total)}
$("addItem").onclick=()=>{const n=$("itemName").value.trim();if(!n)return;shopping.push({name:n,price:+$("itemPrice").value||0,qty:Math.max(1,+$("itemQty").value||1),url:$("itemUrl").value.trim()});$("itemName").value="";$("itemPrice").value="";$("itemQty").value=1;$("itemUrl").value="";renderShopping()};
function metrics(){const target=+$("guestTarget").value||95,assigned=guests.filter(g=>g.table).length,seats=dist().reduce((a,b)=>a+b,0);$("assignedCount").textContent=assigned;$("unassignedCount").textContent=Math.max(0,target-assigned);$("seatCount").textContent=seats;$("tableCountMetric").textContent=dist().length;$("capacity").textContent=`${seats} seats`}
function view(p,t){camera.position.set(...p);orbit.target.set(...t);orbit.update()} $("topView").onclick=()=>view([0,66,.01],[0,0,0]);$("roomView").onclick=()=>view([32,34,42],[0,2,0]);$("windowView").onclick=()=>view([27,12,4],[0,2,0]);$("guestView1").onclick=()=>view([-9,4.8,18],[7,2,-12]);$("guestView2").onclick=()=>view([8,4.8,7],[10,2,-15]);$("coupleView").onclick=()=>view([12,5,-13],[-2,2,8]);
function state(){return{version:3,themeName,floralIntensity,goldIntensity,tableCount:+$("tableCount").value,guestTarget:+$("guestTarget").value,objects:[...objects.values()].map(o=>({id:o.userData.id,type:o.userData.type,pos:o.position.toArray(),rot:o.rotation.y,scale:o.scale.x})),guests,shopping}}
$("saveLocal").onclick=()=>{localStorage.setItem("montBlancWeddingV3",JSON.stringify(state()));$("status").textContent="Layout saved in this browser."};$("loadLocal").onclick=()=>{const raw=localStorage.getItem("montBlancWeddingV3");if(raw)applyState(JSON.parse(raw));else alert("No saved plan found.")};$("downloadPlan").onclick=()=>{const blob=new Blob([JSON.stringify(state(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mont-blanc-wedding-plan.json";a.click();URL.revokeObjectURL(a.href)};$("importPlan").onchange=async e=>{try{applyState(JSON.parse(await e.target.files[0].text()))}catch{alert("Could not read that plan file.")}};
function applyState(s){if(!s)return;$("tableCount").value=s.tableCount||10;$("guestTarget").value=s.guestTarget||95;floralIntensity=s.floralIntensity??.35;goldIntensity=s.goldIntensity??1.25;$("floralIntensity").value=floralIntensity;$("goldIntensity").value=goldIntensity;$("theme").value=s.themeName||"lavender";applyTheme($("theme").value);(s.objects||[]).forEach(x=>{const o=objects.get(x.id);if(o){o.position.fromArray(x.pos);o.rotation.y=x.rot||0;o.scale.setScalar(x.scale||1)}});guests=s.guests||[];shopping=s.shopping||[];renderGuests();renderShopping();metrics()}
function updateLabels(){const w=viewport.clientWidth,h=viewport.clientHeight;labels.forEach((el,obj)=>{const p=new THREE.Vector3();obj.getWorldPosition(p);p.y+=4.1;p.project(camera);el.style.display=$("labelsToggle").checked&&p.z>-1&&p.z<1?"block":"none";el.style.left=(p.x*.5+.5)*w+"px";el.style.top=(-p.y*.5+.5)*h+"px"})}
function resize(){const r=viewport.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(viewport);function loop(){requestAnimationFrame(loop);orbit.update();updateLabels();renderer.render(scene,camera)}resize();applyTheme("lavender");renderShopping();metrics();loop();